app:
  datatunes:
    sql:
      password: ENC[AES256_GCM,data:C3Y4OIYmUkfEI9ZwX6HyI8JeO6sl6rKTee8y3OUdluI=,iv:aG0QYMm2fwATLTeK8QcIY3rrXSo6xA8ZlE9lEayllOQ=,tag:04AqQjc2kXG/o4cbH90ruQ==,type:str]
  mediatunes:
    s3:
      user: ENC[AES256_GCM,data:9oO9kgm+fmiU,iv:ZyZkONfvakP78bBzSoZV8dzDcwPMfkUqztSCZ/fg6P8=,tag:eLomKle/2s2jyoK+2SrfGg==,type:str]
      password: ENC[AES256_GCM,data:0mQxAOPit54dGqR4BRYfWeXdX+wZZ7C0sCmq+oxbo4I=,iv:qtZ/u9p51DMFuWrzyhImCb7C4tA3ONOMyOhHRlYPzeA=,tag:lgXYMdssBX+MnfqAWmsZow==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1v3g2m2yl9jmu53r6h68fkllunvws389nseyp2waarul2m9r3we9sx0gfjt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1SlBmT2hIREFwNkN0Ymt5
        d29tOE41RW83Z0RqMnlNMU8vVXBRcjRQbEZnCm4zekhOeHJDNHMrb2dLVVo0NnJJ
        Q01rTU1FZHJkUHRRamdOOEFkMjQ5NEkKLS0tIC9Ha1pkUVdxTGtRUlltSlVZMUhr
        eTZrUHpCaDdReHp0YllhOVBuNjFxK1EKLU20+u9H0l3OLS07vC3R97kXQkT+YwWO
        vBaxAkuuI7Z6A6JTsOAs7rDUeAPidPHMlaPETV5aK+EyLqhq9s7cOw==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age14uepygtepskwehywergh9fe9j2a3ytqd80y9r2ekfmett6rq3peqjtgxns
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoZUoxenBJRk9vK29PT1Nm
        dkFuZlhZVWZ3Z0xSTThyOW0vczZmeURiREVVCjQwQVk5RjNYUGpZVithMzNwcktO
        bEJMd3JSaTFsQjB6RGdzaHFjaTJ1akEKLS0tIDdZVWgxeDNPTDFNOEpldU9XR3Q5
        cFhXaU1LM05CaElpNVBQTkZnaDk3aDAKZcWaQ7VEyQkQ+6fFBvOeImtuGRCAf5ME
        lTcoO7/AuXGgQ5zLwhANEvViD5rHh/AFYFVLn5AXgSBWKkF6aPErOw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-07-20T09:42:42Z"
  mac: ENC[AES256_GCM,data:GQKCmoOktyT3fEMnrFS1Q0aktub+YxEyEYYF0SZYgKRx+lQwHPPHT0heyRUCVruOjoLxV6DSnqVolpKXG63UrLebXpj8KQxRCN/xH7dQUZWRZ63vb3FhUOtGV/PBUaEu2/WhiDZWt9u5cPRtA+WjQgGEcaeZraIUHIOQnxD4Zoo=,iv:TRBki+DJ7g7sEyeBVTZSfyiNtBF7IenGDv7TFF3V0hc=,tag:4uTUlmTI1Vl5f5wu+Od5nw==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
