# Create ClusterIssuer
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: issuer
spec:
  # Obtain certificates using Certificate Authority represented by a secret
  ca:
    # Use root certificate and private key from this secret
    secretName: cert-manager-config-secrets-issuer
