emerald:
  credentials:
    admin:
      user: ENC[AES256_GCM,data:6AeQ1lk=,iv:CoIe7+LnminvbZHmeD/dUUKmjLQBRjAWZprF22MKdHM=,tag:RIsPohyc9b9eVNnUUWmosw==,type:str]
      password: ENC[AES256_GCM,data:6nePCTz2fkvPq8EKmfs=,iv:qT2XpzcnRIkjQAPWfIwErGxxl3+31Hrj8fcO3F/aJtM=,tag:3yCkzlOxnLtcdecMroD0qA==,type:str]
    readonly:
      user: ENC[AES256_GCM,data:lWufmnqOm7I=,iv:6KZMF8XVydYX8LDtSNwF3qwiW4OP7H6pft7cu1ycTAA=,tag:R1jypjRx6925ygXtnjmNzQ==,type:str]
      password: ENC[AES256_GCM,data:xNSdAmFFdZrEDngDh27sKWEx9UJ/Ko6rq0BGiEkxjRU=,iv:QQGlGPovSCmyaCC8fzTcsAM7QtU08xs9lka/FtyRVdo=,tag:PcDCgUB32hx3cH0fqhkR6A==,type:str]
    readwrite:
      user: ENC[AES256_GCM,data:2CP8rFtSY3k5,iv:jwHsLQIRKxDo9PL0ejNEleV/Lf6dJFsqurfttU/cIAo=,tag:O+PMgnrt2x7NHz8XsJKe4g==,type:str]
      password: ENC[AES256_GCM,data:SJyAR3LSFFVgYVAx8lpyO7uOr18oDwjlY7iB0OLzZf4=,iv:ZTEwLp/R1gV3s6dcToKKypVAnMBNiXmOWBNglE7QTCI=,tag:jwPt/VGATMfcTRfDHzOofA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1v3g2m2yl9jmu53r6h68fkllunvws389nseyp2waarul2m9r3we9sx0gfjt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzNlNoR1NXY3RjR3BqWnJj
        Q0FUTHFqK3dJK3kyYjc5dE9rbkJFRzdRaG04CnNlQ0I2VUl6Tmt2TlNuSDdMQUNM
        MTFxQjJRTFFmZ3E0NkZpN29uTnpwSTgKLS0tIERLQ0NPR2F5aW9rbFBlYlBBMlZ5
        dFRuUVhJZG52UURsaEJ1eFJMeUFSVXMKzVA4kxKnHGHBvRb0FgbrT2By2uKuENAK
        PUqyMWQEbN/NR3+DO+IyZWSEQTdVCxjUqcLOvZM/miOIl+jclD48qA==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age14uepygtepskwehywergh9fe9j2a3ytqd80y9r2ekfmett6rq3peqjtgxns
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtdFJRYnQzUWI5ayswdzdh
        eFg0dHEydk5ObWE4K1JzbnRiRHFaWHBvaldJCll3Ym5zSmtMM1BEVzY1TFRUT08r
        M2VrdTlpSVFsY3VJTkdwYW9jNCtwWU0KLS0tIFpsbUlSTi9TRzFOcFdFQjdJOTE1
        WnBtdUdpSE1WUUpKWUo4bXlJeHBKQXMKoGqTLLRCjk0kzIHF8DP1cIuZ/Gcm3mwa
        rOOBC781EQpuvCe7VlfhTsj2joIsM5shTwGi3s8vfdMVcxbCdwmwdg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-10-21T20:09:31Z"
  mac: ENC[AES256_GCM,data:oA9pL/4i/QDODs2ue67FNpzqxD+b2imOA4l9uPPFJNIBljpLOD5ddh42jVmpEBFKs8TnZml+JZ5ED/YXawobHLCx5g7CNXVJvb7m5jOp/gn2R2h9E0paZV0OkjnuI3Iu30AM33F/qxT5WNfx0O6DMRg1D8BCaiX15NqYuFeirhM=,iv:WLkB9XRqq0nEjMq3ITcaL20GfvsGDw1dK45t3D14g1M=,tag:netQyFHPFMNfoHwxsVGuFA==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
