gecko:
  emerald:
    s3:
      user: ENC[AES256_GCM,data:bd1yfqP/abfr,iv:8maoebafosCuVV8ULDYmc0wgmhXSdJaXcBxkNVXvlok=,tag:0IIg9VP4Jb6MAm6RxMjTYg==,type:str]
      password: ENC[AES256_GCM,data:xqV0C+fVOO9+SaXrbYv+OHg9TTFvVf1/KKP7PyjwnAc=,iv:OkMyyxZNRqDl6ujyPNUZ9zzESR/Fn+izqO7CtmS5as4=,tag:hDlM7Uy7mQGKkQ0SMjob5A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBQWFjK3I1VXJCMDNlOStI
        eklXMy94VDZNOXpabG9uUHF0MG1ab0lzT0M0Ckl2Z1k1b0hzaWZGdmgvaEhMUGIy
        OE5YY3dKT2xLTExoeHRlSmJ0Q2RVTk0KLS0tIE1pbjAxZ2lLSWFwTTdxSzNlZE1v
        dU9lNlNydXk2dkpNeC9wa21FaU9RZGcKuIY667SdBB+omaboy2LNMaR+UwskWQjN
        FgGudhzxtPpz9jb5dkk84WcCI/rZMqqf3LoKR3LCEO8DoSquPWkrBQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1v3g2m2yl9jmu53r6h68fkllunvws389nseyp2waarul2m9r3we9sx0gfjt
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4bGlSNmRNSkxMdWpmM2pl
        SGRIdEQzclhzWWM2Z0QwZWViSWIyNWhLRGdFClZpcFl3TWE2NnZJVFY1eTJNOUlh
        NnpjaDRvNlhycENkSkJkcWgyb1EwOWcKLS0tIFhickhrQ21BMnhCZStRSDdGM3NQ
        R2s0NjlRN0U3bVhqWVdOSjhrYUtrMlUKkLd7HCl9ysGT6P1QlnAMJC2Qba3vsGTa
        fN83aB7LVrPlD6razzgiGhUokA7Qj8kTd5tsBQRVAU68xTqJJviZAQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age14uepygtepskwehywergh9fe9j2a3ytqd80y9r2ekfmett6rq3peqjtgxns
  lastmodified: "2026-10-07T19:19:47Z"
  mac: ENC[AES256_GCM,data:Y6I31XB0Heyi5zX+MffVgxbzcdL2cDHIWdTr1dlPa0CJVaIzT3KA9vK9uTYHGLZRbvLq46gQURKLOpgVKncZgs5oQUxLiVUj7a1NrIOo+Xl1fLpQv8GLcODze9gv20CUzN2HCgFNW1jMqxXVWYnM+RpCx6flqG3kLxgAzcXhsLo=,iv:ubbuum5flxVqEd2NiSrOg1XjdnxP6NjZtHQaiDN+rLo=,tag:Qx4UA9RzfePc2djbNOH5BQ==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.3
