howlite:
  credentials:
    user: ENC[AES256_GCM,data:xy0AXw==,iv:yJ/TEpDjXnn97o7HUuVMWj2Q003KESQ6QhXDOLmegVs=,tag:HmUPBqEFoXRuIgOz9/TnAg==,type:str]
    password: ENC[AES256_GCM,data:RV7nwmU8SEA3S/VMR5wzijzPxlM0TL31GMEkuqCkAY4=,iv:1JLZDLKcuTOvm1xwaK35WCAjdOhoMuYmWvGtCB+Whg4=,tag:8hQEvdyiFMzJH42t9gUcjw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1v3g2m2yl9jmu53r6h68fkllunvws389nseyp2waarul2m9r3we9sx0gfjt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrMGYvd2daWTBhWGpWdjRk
        VGkxbHdOeWZ0cE5oWFpKZkNIY1BKNHlCMVU4CjdyYTdhM0EzejQ1UkdFcUNHWWtu
        VXV3RmtMVy9aOVc5b0FFWGVIMkpGQkEKLS0tIEFzQTNOc0VZaE44dHlvME8yU3Q0
        N0xFMy9nRHNLQTZUQnIzNWZHWC9xazQK7pVKaWrfHUaSag4XLngua8esxXtbuZ7N
        36D/qXNo7CJI2CJXFxKxnDYFFLeL5femoUl1ZOdDF9XEzMcet2/nAw==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age14uepygtepskwehywergh9fe9j2a3ytqd80y9r2ekfmett6rq3peqjtgxns
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEMG5kRGxuKzdkUmhRVnh0
        M0NhS2d5SWhqaFRmczV0S29rMHdRcVZsaEVzCks3dzliUVlyeUpSSHJXOXdZM0ZH
        ZzVIVG5reG5qQW05WjRyUVRmQlpMS1EKLS0tIHJLNENFY0RLem9ub2JpdlE5d0Yw
        SEQycHNGb0REaVhuRzVQRDhPMUlLdzQK+l6eUIWm8U9/lcW5x6bevk3LDdywIEoZ
        /ajc1bzyItqUjMg191dZUAZOKux8oLwHelntuYIlXDqq+8JBBv3kvg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-10-21T20:08:37Z"
  mac: ENC[AES256_GCM,data:lCUlwFfFnD5l+6BlPuymkxofZaGO7vFCVE4nePARx45hpNlX950ipfFyBQgmHtlm9vfzhbdNj5NutLg9ZlrWtByngJhItDbKt++ENx6RIXnxi7DgBFYCmUcmAgavPq0HcGBuOfO2Q2h03ui6yxcaibGsPl6e0hgFu3fYbYiAFwY=,iv:KwzLrB0XulVVv+30s/MV8GzX0d5bxwzLSbFCtY5MPqI=,tag:2uOGo0BUK0ViuKMnhDj8sg==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
