diamond:
  credentials:
    user:
      password: ENC[AES256_GCM,data:7GOlTQrJfkiDPDN7x+5ofYAwXiSig9APXtq6qhsUvRs=,iv:a2J5ihEIoKH8eDu8jYk7VOBDlGiPx6e+plcbqLQ6hk4=,tag:4+1GjQ4eT9cA3U746dsXIw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDNDF4YjdYL2E1QWpQb2I4
        RitSamFVQlF6YXdUNEQ5ckdVdkZZUEJOalc4CmtrQTh1SlZBVkpPK3J2T2g4Vi9z
        OEhjdHRVeXQvRUNvV0o3NzJBUThRbncKLS0tIFNZQnZZSkhFMUIwc3h0SFNRZCtz
        UnpVYlFjSVFmOWpJbHo2QXo1N1RyYzQKiR4d7t05DDiXzqGUf+jqTJ0FRiPCuOFP
        MbMmgML11FPrwI9lJOrkF9pUxw65oGpaucWuNPxsFvYNHSiWXWraPg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1v3g2m2yl9jmu53r6h68fkllunvws389nseyp2waarul2m9r3we9sx0gfjt
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtZU5JSDlWdk90VmR3dGZT
        UnRIeDZRWGVnbmo5OWkwdzNFUlBWSW5oVWpJClFNaWxtV3A2UmZKSTBiZzFRVFhZ
        dDVFL2xUWjJtN09tNkx3WXYwZUkvL1EKLS0tIHZ4SE43UkN3dmxHQmtobllEWFRw
        QlFCZCtUZE5BaVlEK1NGU3FUeW5hdWMKrmaHiJu6uoDTUXJMCtR05hc34yEjO4rU
        H74OIYgi0xsvw8S1wxMBSA0OhIh8PGSjDGBkQdQacVulytelFmiBJg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age14uepygtepskwehywergh9fe9j2a3ytqd80y9r2ekfmett6rq3peqjtgxns
  lastmodified: "2026-10-07T19:13:04Z"
  mac: ENC[AES256_GCM,data:tARmRyMbTIJ189bdsJE39Ad/uQRxzarkcW3ZMfPgJAvaRLOd7EAR/NLFEFWVlLF15EGw0ioWF+zPyvI5sgLFZMuYuTzaZrSvpzeZlLtHjGMkPXApEfbWuqri+R8U0GbGzbYW9p2mvMIA7Zbq0IjMAY95hJJlAQ3jwUq5NWZrvtc=,iv:uIF3qHoVnbpYQKI/C+xK6hUuAz+RHWXzfUY4mxqjDKo=,tag:+S27S2/QjYqHuJ+N2BfQww==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.3
