# Create metallb-config Kustomization
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb-config
spec:
  # Path inside repository to a directory containing Kustomization files
  path: src/clusters/main/infrastructure/metallb/kustomize/metallb-config/kustomize
  dependsOn:
    # Deploy Helm release first
    - name: metallb-helm
  # This key always needs to be here for patching to work
  patches: []
