pelican:
  graphite:
    sql:
      password: ENC[AES256_GCM,data:WIbwiMG9ZHsZgFRcBspj4Ib1ZrfsmcJhsZ6oCgXwYyI=,iv:9fuZ272g5l2s1o8Lztob2gHP2JW26fHe7jx6+Qi0g6c=,tag:G72DaA1HrUbUBCGHQtd5ng==,type:str]
  minium:
    s3:
      user: ENC[AES256_GCM,data:9gE1eoFRep3I,iv:IjuCEqpPYdWt94U0p3niBjwxKtjuDdhIYYqTqd4Aeeg=,tag:W/iI9eKN0Ezw6ib1AJ29Ig==,type:str]
      password: ENC[AES256_GCM,data:zOYlnwPq3mPqXAcnuR+Z+FbmBAuQY8qz0pg45CAGKEM=,iv:6Xeba5j6C2R9AI4MZmPFTkaNhspYHDS96W/fvpuYatg=,tag:hUh2vFRU01x5Xzd1DdaEgQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1SlBmT2hIREFwNkN0Ymt5
        d29tOE41RW83Z0RqMnlNMU8vVXBRcjRQbEZnCm4zekhOeHJDNHMrb2dLVVo0NnJJ
        Q01rTU1FZHJkUHRRamdOOEFkMjQ5NEkKLS0tIC9Ha1pkUVdxTGtRUlltSlVZMUhr
        eTZrUHpCaDdReHp0YllhOVBuNjFxK1EKLU20+u9H0l3OLS07vC3R97kXQkT+YwWO
        vBaxAkuuI7Z6A6JTsOAs7rDUeAPidPHMlaPETV5aK+EyLqhq9s7cOw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1v3g2m2yl9jmu53r6h68fkllunvws389nseyp2waarul2m9r3we9sx0gfjt
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoZUoxenBJRk9vK29PT1Nm
        dkFuZlhZVWZ3Z0xSTThyOW0vczZmeURiREVVCjQwQVk5RjNYUGpZVithMzNwcktO
        bEJMd3JSaTFsQjB6RGdzaHFjaTJ1akEKLS0tIDdZVWgxeDNPTDFNOEpldU9XR3Q5
        cFhXaU1LM05CaElpNVBQTkZnaDk3aDAKZcWaQ7VEyQkQ+6fFBvOeImtuGRCAf5ME
        lTcoO7/AuXGgQ5zLwhANEvViD5rHh/AFYFVLn5AXgSBWKkF6aPErOw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age14uepygtepskwehywergh9fe9j2a3ytqd80y9r2ekfmett6rq3peqjtgxns
  lastmodified: "2026-10-07T19:20:28Z"
  mac: ENC[AES256_GCM,data:gjVw7B8XTpccwypqYsOnm1rPO516LHhs7CCLeOYiHL4bqWWuegMG9adUUSXQMyJz5LeUgYKee4vXE2PxyXTQGdOY9Mo9poJwEmCgMghg5pay1KK4zwYm5R8r4ZFAMsa+a99g01ARqwnHv0fDiIHrh4fajbNiQuMNjNIIt2dDLC0=,iv:SIhzbVyD5Yt/OZAO5AYcO2NqpZPXeGSYf4osppb3HCI=,tag:U8vStLhnNDnG7jZM9j3dPg==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.3
