app:
  mediarecords:
    s3:
      user: ENC[AES256_GCM,data:IKSXYdMF6aix,iv:NU/ifxW8x+nCOykjsa5dftmtiNPJEN0uK4xK6o3B8Pc=,tag:XM8U1vA2jBPoHeqI11Sg7A==,type:str]
      password: ENC[AES256_GCM,data:6AR2xYUSTwdxHXFQ0FnxlMXhzzqlvHqzEad9oXrb5b4=,iv:1Df3b/p+YR4sPaXpy9Q+S6ebElzDqepex/Wb8DKdIME=,tag:w+0bxOhECEGRfgJUYJa5pA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1v3g2m2yl9jmu53r6h68fkllunvws389nseyp2waarul2m9r3we9sx0gfjt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBQWFjK3I1VXJCMDNlOStI
        eklXMy94VDZNOXpabG9uUHF0MG1ab0lzT0M0Ckl2Z1k1b0hzaWZGdmgvaEhMUGIy
        OE5YY3dKT2xLTExoeHRlSmJ0Q2RVTk0KLS0tIE1pbjAxZ2lLSWFwTTdxSzNlZE1v
        dU9lNlNydXk2dkpNeC9wa21FaU9RZGcKuIY667SdBB+omaboy2LNMaR+UwskWQjN
        FgGudhzxtPpz9jb5dkk84WcCI/rZMqqf3LoKR3LCEO8DoSquPWkrBQ==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age14uepygtepskwehywergh9fe9j2a3ytqd80y9r2ekfmett6rq3peqjtgxns
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4bGlSNmRNSkxMdWpmM2pl
        SGRIdEQzclhzWWM2Z0QwZWViSWIyNWhLRGdFClZpcFl3TWE2NnZJVFY1eTJNOUlh
        NnpjaDRvNlhycENkSkJkcWgyb1EwOWcKLS0tIFhickhrQ21BMnhCZStRSDdGM3NQ
        R2s0NjlRN0U3bVhqWVdOSjhrYUtrMlUKkLd7HCl9ysGT6P1QlnAMJC2Qba3vsGTa
        fN83aB7LVrPlD6razzgiGhUokA7Qj8kTd5tsBQRVAU68xTqJJviZAQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-08-22T17:40:09Z"
  mac: ENC[AES256_GCM,data:MNXHonVraZkWla9cdRk5KR6w/Buli9VZD6B46tBkn3HQnBEPGG6tozwWGmAFWHOLcG/XQEabAvjD+4SOxZml0WSuvvwulY3q48jl8wmfdP7oTWCgE098eMb+lxvbmtbSitOJZmJVlF7cSngTfh6WoiPqCmimWs2gQoQ0CKibrPY=,iv:JI8xsXyCouHrZ/Jh3xjiSmjGnC3XFbnZnWStvUIZ9CA=,tag:nNRWrImMMrBfITtVCTmttQ==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
