# Create cert-manager-config Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# Include the following configuration files
configurations:
  - configurations/names.yaml
# Include the following resources
resources:
  - resources/issuer.yaml
# Generate secrets
secretGenerator:
  - files:
      - tls.crt=secrets/tls.crt.json
      - tls.key=secrets/tls.key.json
    name: cert-manager-config-secrets-issuer
