# Create jasmine Helm release
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jasmine
spec:
  chart:
    spec:
      # Use this chart from the repository
      chart: jasmine
      # Pin version to major
      version: "0.x"
      # Use this Helm repository
      sourceRef:
        kind: HelmRepository
        name: radio-aktywne
  # This key always needs to be here for patching to work
  postRenderers: []
  values:
    jasmine:
      urls:
        public: https://jasmine.k8s.radioaktywne.pl
      scorpion:
        public:
          scheme: https
          host: scorpion.k8s.radioaktywne.pl
          port: null
      debug: false
    container:
      spec:
        env:
          # Add extra certificates for Node.js to trust
          - name: NODE_EXTRA_CA_CERTS
            value: /app/certs/certificates.crt
        volumeMounts:
          # Mount trust-manager certificates
          - name: trust-manager-certificates
            mountPath: /app/certs/
            readOnly: true
    pod:
      spec:
        volumes:
          - name: trust-manager-certificates
            configMap:
              name: trust-manager-certificates-bundle
  valuesFrom:
    - kind: Secret
      name: jasmine-helm-secrets-values
      valuesKey: values.yaml
