falcon:
  secrets:
    default:
      - ENC[AES256_GCM,data:YTLRqAu65d/+dkor+9NNBMt8dO42pCKyajlZd9LZImI=,iv:WRkseR/DV5UQrV6YxkK2OnwZd5ExFMc95zP2gB71WJk=,tag:jKpyCF20SopGKKM9V7CZeQ==,type:str]
    cookie:
      - ENC[AES256_GCM,data:cFQUaPclxAowZzOfCZFZLhWDvT59OTC+edO4b/pKA3o=,iv:lvKZYFa8mVsJWOMy/DeM34vwiiGd/8r4LpFM60ATIms=,tag:tdCZgze3WME13hsEB4jtxw==,type:str]
    cipher:
      - ENC[AES256_GCM,data:ok51qiViimzJHMJM8O29ni4t1jwxFz9YkmbrWtO0J7U=,iv:fG/vyLDDVYxTF3MySm72bXksYeP21gaydRCsHAuzJU4=,tag:e7QStz5wO1pCO1fUi8hXsw==,type:str]
  obsidian:
    sql:
      password: ENC[AES256_GCM,data:oDB5J37q2Cxg5l51M7ZrYKVn2nycdWMcBNm1HIoVh8A=,iv:Dbm9lIY10unAfY4O6hD9jqCO6Oy0mIVWriVRiHopkO0=,tag:hdLJKsbmSwVropcUY4lS5A==,type:str]
  oidc:
    google:
      client: ENC[AES256_GCM,data:PeM+++KlMAOOaA2yBm4t+YWPlu8zde/Yqr9t7uJH3EuHct5K34ic74ipVYSiaU2yvqIZlMXOZyoqpTbb4ZYqOKTGY0Vx2ClN,iv:s799+julprEyMhb6AHYiWbw1AXuLvF0Lv5JQuY6lFuk=,tag:UB1OrgU/uPy+SIDt8DCR+w==,type:str]
      secret: ENC[AES256_GCM,data:nbm+HIP+g6AVgiBMLYrvfN7rsRIfM46rW5JsbqB/8+dwviE=,iv:Z4LpfwGarvVXz5h/w3KrX+W6P+L6jMKrQakjUDxChrI=,tag:xhuHX7HnAby9C8IwYi3N9A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1SlBmT2hIREFwNkN0Ymt5
        d29tOE41RW83Z0RqMnlNMU8vVXBRcjRQbEZnCm4zekhOeHJDNHMrb2dLVVo0NnJJ
        Q01rTU1FZHJkUHRRamdOOEFkMjQ5NEkKLS0tIC9Ha1pkUVdxTGtRUlltSlVZMUhr
        eTZrUHpCaDdReHp0YllhOVBuNjFxK1EKLU20+u9H0l3OLS07vC3R97kXQkT+YwWO
        vBaxAkuuI7Z6A6JTsOAs7rDUeAPidPHMlaPETV5aK+EyLqhq9s7cOw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1v3g2m2yl9jmu53r6h68fkllunvws389nseyp2waarul2m9r3we9sx0gfjt
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoZUoxenBJRk9vK29PT1Nm
        dkFuZlhZVWZ3Z0xSTThyOW0vczZmeURiREVVCjQwQVk5RjNYUGpZVithMzNwcktO
        bEJMd3JSaTFsQjB6RGdzaHFjaTJ1akEKLS0tIDdZVWgxeDNPTDFNOEpldU9XR3Q5
        cFhXaU1LM05CaElpNVBQTkZnaDk3aDAKZcWaQ7VEyQkQ+6fFBvOeImtuGRCAf5ME
        lTcoO7/AuXGgQ5zLwhANEvViD5rHh/AFYFVLn5AXgSBWKkF6aPErOw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age14uepygtepskwehywergh9fe9j2a3ytqd80y9r2ekfmett6rq3peqjtgxns
  lastmodified: "2026-10-07T19:19:15Z"
  mac: ENC[AES256_GCM,data:0N8jhNN0naaqcj390VX31zoLKEkaOC70m/bDbbt9Q3FiMYLTQFqP+1NktsDtorkArZOc6oz+P53PomhjCUe62SB5lsJhTOCAqvLC6XCdNVVTixNxVO/nliLi9xm73UA5He/407+WriZ02O8HuO2JCzB6Hxng680t167y9KQK4QY=,iv:gJPK+/3VeqIJASsr5tBYgMozA03AfGT9/j6ju8r4u20=,tag:ZQ0WleI4264Ns1C5KZxQrg==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.3
