graphite:
  credentials:
    user:
      password: ENC[AES256_GCM,data:xXmFqi/JFGFsuao64RJmydcQvw3mjYA/i4Rkm9cWNH8=,iv:ZRxKnhEAml/Zz8ztOQTTGDogdIdBfz8DVlQuA30euW8=,tag:v+5YsD/acvnjf7oXBNRA0Q==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDNDF4YjdYL2E1QWpQb2I4
        RitSamFVQlF6YXdUNEQ5ckdVdkZZUEJOalc4CmtrQTh1SlZBVkpPK3J2T2g4Vi9z
        OEhjdHRVeXQvRUNvV0o3NzJBUThRbncKLS0tIFNZQnZZSkhFMUIwc3h0SFNRZCtz
        UnpVYlFjSVFmOWpJbHo2QXo1N1RyYzQKiR4d7t05DDiXzqGUf+jqTJ0FRiPCuOFP
        MbMmgML11FPrwI9lJOrkF9pUxw65oGpaucWuNPxsFvYNHSiWXWraPg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1v3g2m2yl9jmu53r6h68fkllunvws389nseyp2waarul2m9r3we9sx0gfjt
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtZU5JSDlWdk90VmR3dGZT
        UnRIeDZRWGVnbmo5OWkwdzNFUlBWSW5oVWpJClFNaWxtV3A2UmZKSTBiZzFRVFhZ
        dDVFL2xUWjJtN09tNkx3WXYwZUkvL1EKLS0tIHZ4SE43UkN3dmxHQmtobllEWFRw
        QlFCZCtUZE5BaVlEK1NGU3FUeW5hdWMKrmaHiJu6uoDTUXJMCtR05hc34yEjO4rU
        H74OIYgi0xsvw8S1wxMBSA0OhIh8PGSjDGBkQdQacVulytelFmiBJg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age14uepygtepskwehywergh9fe9j2a3ytqd80y9r2ekfmett6rq3peqjtgxns
  lastmodified: "2026-10-07T19:13:47Z"
  mac: ENC[AES256_GCM,data:gVjKvMTzy4g1MlcmRUTekTq+ix9NiaxJm+rxQAPU5ldJDcmtojbD4UNdRl/mN/mKOeovbL0l6jb5tbpK61TDo20rPsWY4eVilm6LNWZazVVtA3Y3flCTCOJVmMMI0UPYxcIsfbNZqVnxl1jwT4yrWTrGcYDf0GFDslzVl9IS6Q4=,iv:OtzdGtHPM3WPdkJW873t8UJubtrq6DhNDA8EXzjMAXM=,tag:eSJvqGHVYZXcOayUE4Z7cg==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.3
