graphite:
  credentials:
    root:
      password: ENC[AES256_GCM,data:BDw8yV+ampznrrxpbvg=,iv:hZSY/0wGehw1MtGJNmSCXdJ3nXbNWC4WNi2Ejo8p8XE=,tag:peITF+XGlYM92v9g3tMFQQ==,type:str]
    user:
      password: ENC[AES256_GCM,data:xXmFqi/JFGFsuao64RJmydcQvw3mjYA/i4Rkm9cWNH8=,iv:ZRxKnhEAml/Zz8ztOQTTGDogdIdBfz8DVlQuA30euW8=,tag:v+5YsD/acvnjf7oXBNRA0Q==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1v3g2m2yl9jmu53r6h68fkllunvws389nseyp2waarul2m9r3we9sx0gfjt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDNDF4YjdYL2E1QWpQb2I4
        RitSamFVQlF6YXdUNEQ5ckdVdkZZUEJOalc4CmtrQTh1SlZBVkpPK3J2T2g4Vi9z
        OEhjdHRVeXQvRUNvV0o3NzJBUThRbncKLS0tIFNZQnZZSkhFMUIwc3h0SFNRZCtz
        UnpVYlFjSVFmOWpJbHo2QXo1N1RyYzQKiR4d7t05DDiXzqGUf+jqTJ0FRiPCuOFP
        MbMmgML11FPrwI9lJOrkF9pUxw65oGpaucWuNPxsFvYNHSiWXWraPg==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age14uepygtepskwehywergh9fe9j2a3ytqd80y9r2ekfmett6rq3peqjtgxns
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtZU5JSDlWdk90VmR3dGZT
        UnRIeDZRWGVnbmo5OWkwdzNFUlBWSW5oVWpJClFNaWxtV3A2UmZKSTBiZzFRVFhZ
        dDVFL2xUWjJtN09tNkx3WXYwZUkvL1EKLS0tIHZ4SE43UkN3dmxHQmtobllEWFRw
        QlFCZCtUZE5BaVlEK1NGU3FUeW5hdWMKrmaHiJu6uoDTUXJMCtR05hc34yEjO4rU
        H74OIYgi0xsvw8S1wxMBSA0OhIh8PGSjDGBkQdQacVulytelFmiBJg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-10-21T20:08:58Z"
  mac: ENC[AES256_GCM,data:qJH8SRcDOxz51x5d/eKX9JBu+SHn+BposgMgd3yGBsAmzjNxMjGKUyR/6z+LuMQdnr3f87QiIb5A1INEC+P7s/BlPgNlcxnKvDqPAYydVJ2UE4nj2ja7SeJDTbqFDzYOanNPFPlQBwL0UqYE5q4vjdcyZV3XKlTPIQOvMEFYOEA=,iv:b3y2umgQ7bRxEgKJuXlVGCjFT8mnfCo+Rut3fKHMizs=,tag:fsrEyrV2Du5ub9Ez10XYgQ==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
