scorpion:
  clients:
    traefik:
      client_secret: ENC[AES256_GCM,data:Y00foOSjWi0O1ptVb9Y8t4VKmYzMAkT7G7JlvgQRVps=,iv:mmPSh8akFIPzCesR9rY0ZeBQFAPoIfTZMaBmh1JniC4=,tag:6izwMG9HO1UbeagbSHRzaQ==,type:str]
  diamond:
    sql:
      password: ENC[AES256_GCM,data:diWETwf2EwC1Pa/h1mMIU1U3kzauleDzKzO5Fr4dZYA=,iv:rcFgGKleKAox8CZsng9wct+4nZdZi/bLhaY9G5tdc2k=,tag:pE3PjI3kEuCcj9mWlLOGUA==,type:str]
  secrets:
    cookie:
      - ENC[AES256_GCM,data:Mj3e2gFyF6wOJ/+NzI+0g/r2S4OF2JQYZPMvQquGrf0=,iv:c10PnOh1AEAWNPuYCkbZG2C5SP5C2F9alM0MI1RJPh0=,tag:BOkkpezh7vjKGFhtawKsSg==,type:str]
    system:
      - ENC[AES256_GCM,data:1STg6GnKb9NxZ/HC09wm/leIVdOVG9LbI08eGwOunj8=,iv:/rEG5GNiE5Vh8ZEM5J+g/J//3z8fq4GLV1+j8RErFBI=,tag:dJ/p0xcWmCQGLDAYJXiWoA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1SlBmT2hIREFwNkN0Ymt5
        d29tOE41RW83Z0RqMnlNMU8vVXBRcjRQbEZnCm4zekhOeHJDNHMrb2dLVVo0NnJJ
        Q01rTU1FZHJkUHRRamdOOEFkMjQ5NEkKLS0tIC9Ha1pkUVdxTGtRUlltSlVZMUhr
        eTZrUHpCaDdReHp0YllhOVBuNjFxK1EKLU20+u9H0l3OLS07vC3R97kXQkT+YwWO
        vBaxAkuuI7Z6A6JTsOAs7rDUeAPidPHMlaPETV5aK+EyLqhq9s7cOw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1v3g2m2yl9jmu53r6h68fkllunvws389nseyp2waarul2m9r3we9sx0gfjt
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoZUoxenBJRk9vK29PT1Nm
        dkFuZlhZVWZ3Z0xSTThyOW0vczZmeURiREVVCjQwQVk5RjNYUGpZVithMzNwcktO
        bEJMd3JSaTFsQjB6RGdzaHFjaTJ1akEKLS0tIDdZVWgxeDNPTDFNOEpldU9XR3Q5
        cFhXaU1LM05CaElpNVBQTkZnaDk3aDAKZcWaQ7VEyQkQ+6fFBvOeImtuGRCAf5ME
        lTcoO7/AuXGgQ5zLwhANEvViD5rHh/AFYFVLn5AXgSBWKkF6aPErOw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age14uepygtepskwehywergh9fe9j2a3ytqd80y9r2ekfmett6rq3peqjtgxns
  lastmodified: "2026-10-07T19:21:14Z"
  mac: ENC[AES256_GCM,data:2I1dQIuuJD5Di1fBgZaorPJs3r78/52l9vg44qKxtRFTozMrzWibPqKrG+q2wJMVyIEOohUgL8mp8/UOyO6TgZ1vjEwfGkM6o+D//HMiSdlKJWBL1+bGKYnfT2hG8jOeGoRluhjKX0CYnLl6dfm/OvbdNWVqxuinvRUI6oCglbo=,iv:IMakGX5swlk6h9bHueP8LsTxglmVwIc3/keD39LQCHU=,tag:HO72BT/X5mO0evL+WedNGw==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.3
