obsidian:
  credentials:
    root:
      password: ENC[AES256_GCM,data:1YTduWq3xfQC+OAIZas=,iv:0d6ayNiQa1YGyzsNWZVgCFA3gIGPgdcEmEzXPk10r8g=,tag:bsFrEk59oyVRWyldIFhaww==,type:str]
    user:
      password: ENC[AES256_GCM,data:j26FjmcuTQSoo3QamSQQSf91tuA1ZawOmhUiPAqduk4=,iv:/k57iblZwstxbprcyiM3ZgHSgLn/5g7aOwK+7YKgzHo=,tag:MQcxbEcAyvNSUg6mzjJ01g==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1v3g2m2yl9jmu53r6h68fkllunvws389nseyp2waarul2m9r3we9sx0gfjt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDNDF4YjdYL2E1QWpQb2I4
        RitSamFVQlF6YXdUNEQ5ckdVdkZZUEJOalc4CmtrQTh1SlZBVkpPK3J2T2g4Vi9z
        OEhjdHRVeXQvRUNvV0o3NzJBUThRbncKLS0tIFNZQnZZSkhFMUIwc3h0SFNRZCtz
        UnpVYlFjSVFmOWpJbHo2QXo1N1RyYzQKiR4d7t05DDiXzqGUf+jqTJ0FRiPCuOFP
        MbMmgML11FPrwI9lJOrkF9pUxw65oGpaucWuNPxsFvYNHSiWXWraPg==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age14uepygtepskwehywergh9fe9j2a3ytqd80y9r2ekfmett6rq3peqjtgxns
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtZU5JSDlWdk90VmR3dGZT
        UnRIeDZRWGVnbmo5OWkwdzNFUlBWSW5oVWpJClFNaWxtV3A2UmZKSTBiZzFRVFhZ
        dDVFL2xUWjJtN09tNkx3WXYwZUkvL1EKLS0tIHZ4SE43UkN3dmxHQmtobllEWFRw
        QlFCZCtUZE5BaVlEK1NGU3FUeW5hdWMKrmaHiJu6uoDTUXJMCtR05hc34yEjO4rU
        H74OIYgi0xsvw8S1wxMBSA0OhIh8PGSjDGBkQdQacVulytelFmiBJg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-12T17:02:04Z"
  mac: ENC[AES256_GCM,data:xWlB8WpXRVRmPNaAd2qANuyT3/D9Ml4V8WCzsI3Ggb038jy+2B8kXpiV+Tj5mBuCI39pUyWfLJ1WCu6YhiSa/Ts7ExlzU5e5+gAVbb0bKp/zbxfIxZsF20lsaX4US0Bg9LuOMfWXsjtOAQi5jPAIQYu3ZszBW8cEGvTiI05JDgQ=,iv:jFTCgYQXiecF3ItjmNbA3uYk4dS6aFpxNiDMSSluZyY=,tag:LqPGq1mbQKqGsZC0iokEww==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
