# Configure names transformer
nameReference:
  - kind: Secret
    fieldSpecs:
      # Replace secret names in ClusterIssuer
      - group: cert-manager.io
        kind: ClusterIssuer
        path: spec/ca/secretName
