quokka:
  credentials:
    source:
      user: ENC[AES256_GCM,data:knBK/hSS,iv:bCmiOmWw2PzwxUdhh7OMVdqMhwfdKa10WSUP16uibX4=,tag:3r/lz+u9cBdcSuXLDEUQNg==,type:str]
      password: ENC[AES256_GCM,data:m68Y2D8ic4lsOxwkW2RHltKZfgxzoPKYLRY0t6pfevs=,iv:VcfjGKkXOHI61oeWR0BEc2S1HA5zC66iENYUPnvu8MI=,tag:UtT9TjlPQ0kYLUo16sbTBw==,type:str]
    admin:
      user: ENC[AES256_GCM,data:QYE67IU=,iv:5RuE5NSYDPLMvEIY9oiOKBXbo9widk7yBZ6AywDFFOs=,tag:lUmxy3O9KqPw7dku8nFGjA==,type:str]
      password: ENC[AES256_GCM,data:fwFBfOYs9JXHTUe3d8I=,iv:zrMKwiZF7zYNgWn1EG5rj31/1f9G7boK1rx6VxP8/5g=,tag:YWOl2BY+YrU3vOn3vNi+KA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyTE10ODRvM1FWYVI1ejNy
        NTgxdG9tTUtqUlhtQzRjWW9OSVcyRlpPcWpBClFmTUp4TlNtVWhjdmlTcjQ1elFn
        YVEyWm9md1E3OFc4Y2lMUkVMQktpU1EKLS0tIDJ2N1hKck16WmVtMjBMYlFQWEJS
        UU1tc1NwR0c1MU5RSEdkbENHQ1liY00K0TAXGmnr0vB6xBzhf6nWCogenVHYKjYn
        fnKEy+UOccTE5wQ3xXqgo94ndoKKEhZ8GmS6yj2nrcClUrIz5N8GZw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1v3g2m2yl9jmu53r6h68fkllunvws389nseyp2waarul2m9r3we9sx0gfjt
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKUkFwbCtIZGpqSUcwZmZE
        SW4rRFczdEtrTUowcDVUUnEzbWtOa1pZU0RrCnU4Mi94eXovUmJXaFJOUFNvd3Rn
        MXVEdnJ6MlU3S2pxeDlNQ3JyT01zTDAKLS0tIGF3QnJGaWhjd0VOcDF4em5FSTBV
        MkhWa29wT3RzaTVRc0lJQnlTc2Q5cFUK2bvxxP7QLyJE0p+5ShJcfT7BAloa/Noe
        3tSPfmqaTzt2mmzLhXBTGsUSnpOoc5noMFXz+ZIWus2jO/N3kYCV7A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age14uepygtepskwehywergh9fe9j2a3ytqd80y9r2ekfmett6rq3peqjtgxns
  lastmodified: "2026-10-07T19:20:57Z"
  mac: ENC[AES256_GCM,data:9hu/Bdly+OTLR7tv47+oZqWF+Wd/Tm4bIjq60Lug7bSnrOnORgeCImSsaO7mJnDBBXLVC5zL0x12+JCGUzpsf1sX3CoVJXJNlXzHxWY4ZB1W+WYukyluURKzcSHS2GGHc+UBHxgrWc1xmnUIgzeuLCnOBBgd9KYg4OVXthcJrDs=,iv:m12fo1nba2DIkr1UqNgA1Xn/vj7AAKGVgjZinqEoTwQ=,tag:qL2PYGDgzTc9ywL5OiQI/g==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.3
