minium:
  credentials:
    admin:
      user: ENC[AES256_GCM,data:ngmmWl8=,iv:Bo9gRDHfwwgcAiMfynICv4q5+6n/Z3ewNtwFoy3UHcM=,tag:d+SOlXNGQtoJbQCt/mbsgw==,type:str]
      password: ENC[AES256_GCM,data:c5DK2zbQBM3pZxMWYYE=,iv:ww7tMhg4Nx7EQzSJ2dwQyuzoTroigUiu1mng0W4sPWg=,tag:qKuolUvF0B5pW764OQ/bww==,type:str]
    readonly:
      user: ENC[AES256_GCM,data:pn0MV2OWsBs=,iv:zk6MJNigas1vcmt2Kv5Mv00MiHvdMrihS1h9VvrJecE=,tag:XxP5Qqs+ad3wVV28xj1GhA==,type:str]
      password: ENC[AES256_GCM,data:5tVz/32wzoO+hxHFU7n3ALPlbtID0bioPc4Q8PLmueY=,iv:/WjvkuKmQD55gVqvBqmOPSfmubn/6QaVqTWeXXvXAwA=,tag:97/4Bohz0W8oiVVoHw1P0w==,type:str]
    readwrite:
      user: ENC[AES256_GCM,data:iJrE0N8BJd4z,iv:Ka9ozgI/f1Ql9WaDGQAg0EDFaBZzEtUxxGDMYC7F71c=,tag:BVvkfOr17wKehqLPQDxfOg==,type:str]
      password: ENC[AES256_GCM,data:CLoYqwOv8PkdjftzsooCsKkE4lmdfZZshoHdVkOS6KY=,iv:C4wb3k8R4+ozLORHdglAwSTeDFtyBrXxL+xGK1Tklac=,tag:5+mPnG05pbhHS8p/06Iu4A==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1v3g2m2yl9jmu53r6h68fkllunvws389nseyp2waarul2m9r3we9sx0gfjt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzNlNoR1NXY3RjR3BqWnJj
        Q0FUTHFqK3dJK3kyYjc5dE9rbkJFRzdRaG04CnNlQ0I2VUl6Tmt2TlNuSDdMQUNM
        MTFxQjJRTFFmZ3E0NkZpN29uTnpwSTgKLS0tIERLQ0NPR2F5aW9rbFBlYlBBMlZ5
        dFRuUVhJZG52UURsaEJ1eFJMeUFSVXMKzVA4kxKnHGHBvRb0FgbrT2By2uKuENAK
        PUqyMWQEbN/NR3+DO+IyZWSEQTdVCxjUqcLOvZM/miOIl+jclD48qA==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age14uepygtepskwehywergh9fe9j2a3ytqd80y9r2ekfmett6rq3peqjtgxns
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtdFJRYnQzUWI5ayswdzdh
        eFg0dHEydk5ObWE4K1JzbnRiRHFaWHBvaldJCll3Ym5zSmtMM1BEVzY1TFRUT08r
        M2VrdTlpSVFsY3VJTkdwYW9jNCtwWU0KLS0tIFpsbUlSTi9TRzFOcFdFQjdJOTE1
        WnBtdUdpSE1WUUpKWUo4bXlJeHBKQXMKoGqTLLRCjk0kzIHF8DP1cIuZ/Gcm3mwa
        rOOBC781EQpuvCe7VlfhTsj2joIsM5shTwGi3s8vfdMVcxbCdwmwdg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-10-21T20:09:48Z"
  mac: ENC[AES256_GCM,data:Fz6AltwWvjbiex/T7ALvwqWOjQn8pVpQhswl0MjNwx5i6YLRIT8lp7W/D4F2fTv2/Yle0a1CBM3w6O1bXV0ZbzYTvfT1oFfliW5kvrHn+5J/xxQAFX/OyE1d6Nms1ccaj64GKDBgg//QRjXKHj6PZkegpvTtNk0mNlnftDGpiFI=,iv:EBGCnCmOpxxZAUyLf0hLxV945nlQiTfpaqTO5InSgs8=,tag:eejFTLyyxM4uXuZW9eSROw==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
