# Create orchid Helm release
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: orchid
spec:
  chart:
    spec:
      # Use this chart from the repository
      chart: orchid
      # Pin version to major
      version: "0.x"
      # Use this Helm repository
      sourceRef:
        kind: HelmRepository
        name: radio-aktywne
  # This key always needs to be here for patching to work
  postRenderers: []
  values:
    orchid:
      urls:
        public: https://orchid.k8s.radioaktywne.pl
      falcon:
        public:
          scheme: https
          host: falcon.k8s.radioaktywne.pl
          port: null
      crocus:
        public:
          scheme: https
          host: crocus.k8s.radioaktywne.pl
          port: null
      oidc:
        google:
          domain: radioaktywne.pl
    container:
      spec:
        env:
          # Add extra certificates for Node.js to trust
          - name: NODE_EXTRA_CA_CERTS
            value: /app/certs/certificates.crt
        volumeMounts:
          # Mount trust-manager certificates
          - name: trust-manager-certificates
            mountPath: /app/certs/
            readOnly: true
    pod:
      spec:
        volumes:
          - name: trust-manager-certificates
            configMap:
              name: trust-manager-certificates-bundle
  valuesFrom:
    - kind: Secret
      name: orchid-helm-secrets-values
      valuesKey: values.yaml
