app:
  emicast:
    icy:
      user: ENC[AES256_GCM,data:f8iU9lhT,iv:XD2XjBst2Sq3/4/GN6AH9TRpMa9sCNlubxTvbor6zx8=,tag:8pbzNcQVPS9lg9Vp5eSNSQ==,type:str]
      password: ENC[AES256_GCM,data:t/pAQswbikv0IBaT2jLU5zoar+3Zzak6lzH6MidJ6zM=,iv:ALFQcJ3K96OwGua/lbIdFW63j9EKX6r1OJ2Js9RhCNc=,tag:h/lNH8NPnDxOdTy0+fiYGQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1v3g2m2yl9jmu53r6h68fkllunvws389nseyp2waarul2m9r3we9sx0gfjt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqT01DWEdadUpTNzlkQ0p3
        N2NUUi9wc1BBTWxndE9CaGpmWEJzMUNWbFgwClBCNHQ4LzBMS2ZtWjV4VVc4OWZ1
        a2dUeTBEUnFpQ0RUVStHTERNMit0RU0KLS0tIERzdzlsTFN0Z2srSFZxUGM4VWVF
        RHR2NEkrZTgwS1N6c3FXNVVueWZSUmsKbdOZerqwD8dehdvkTJHzPA2gjQWWZ+JP
        2js9hT8Zeb0TTpz9wRJ3LrBHwIsf0yLi7dOCzcr9AoLSyhjXQZl8aA==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age14uepygtepskwehywergh9fe9j2a3ytqd80y9r2ekfmett6rq3peqjtgxns
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4NEFQdnlNc2daMnZjbE5a
        OGhPcWtBeDZJMWgzV1ZaeVBnZjlxQVROeTJBClJZWnlodm1Rdlg2VnBDck9lZnhW
        dHlQUm5XVXlWenpGem5KSmtrM21iaGsKLS0tIGwremVodGpLRWVSSzlFSE9ER3Js
        UDBxOUlMMldUSStXRjFSLzJEL0NXQlEKmWF1sc/1OheIGLjJMxQUELIKVloVBrmy
        +EBUErPj63keJ807u3qYrCoqfUZtyWCM6D/GpUgn/9br2DcTRgRTvw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-07-26T16:31:17Z"
  mac: ENC[AES256_GCM,data:CVJDichM9HBgDytunpAyf6z5gWTBfHFn5aB776jaPht1R8KLvBLSXiXd+LDWwB6kr2rsPtt9kl4lU1fdh3W3lIHTkjMpCpvpR2S0QHhC9MZAX5Km4kC2pwMEqsx8yiE3EE5hI814T/w3ZcZpINB56WLqo61QB6m+G6BhQbhDKBU=,iv:UczAPbPC17fdrO2ydU3eATgJTxLy1WPUgD2s18G0hDA=,tag:6jhqQaq13N1fkEiUVzxZEg==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
