database:
  credentials:
    admin:
      user: ENC[AES256_GCM,data:E/dAtH0=,iv:9Z+KShbzJBdaS3FaT/Fp8sNAgDi3b354fECC7NW7xs4=,tag:pj4Ub33Aq198sDmwld5gaQ==,type:str]
      password: ENC[AES256_GCM,data:FgIAPpZonflqTzmrNlY=,iv:TKllDJjH2S9JlrktqwIPO4ZcupVLZGRfUSWMHXRwaxc=,tag:vJ46/YTBPWs6P59AwvqKhQ==,type:str]
    readonly:
      user: ENC[AES256_GCM,data:Ka6wK/d1sjc=,iv:ZckVQovrU3GQOmxGxLZMwlHvhmyvQoEW6vI/PYzcd3Y=,tag:QBEeve+GQPB9t+FmejejjQ==,type:str]
      password: ENC[AES256_GCM,data:/gMim1UiYYSYEDOctzGsWgweyVGSUZGjJ/HHQZixY6w=,iv:NvDrfigRPzoOHWr1/2AgsK8IDG9Y6OSKJAjcFfpdXHg=,tag:fskLYGJyf9KTtmC38Ijvyw==,type:str]
    readwrite:
      user: ENC[AES256_GCM,data:HZgjbpbFrtot,iv:ZpMUiy4tLKGS/qDn5z8GwR8V+pk1c/dqJwi4cyeQGqg=,tag:pkFLYPwMUs8kFRIBn/S8mg==,type:str]
      password: ENC[AES256_GCM,data:+bMSG2euI2yQOXFJV1J+zJefATgaEzOxNPK4JZ88+l4=,iv:O65gO2J7uVToe1FwG77myxdk3TBJSUqTZfRyryE1p68=,tag:QMdSeMS/47rXWvTXVcpZ+A==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1v3g2m2yl9jmu53r6h68fkllunvws389nseyp2waarul2m9r3we9sx0gfjt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzNlNoR1NXY3RjR3BqWnJj
        Q0FUTHFqK3dJK3kyYjc5dE9rbkJFRzdRaG04CnNlQ0I2VUl6Tmt2TlNuSDdMQUNM
        MTFxQjJRTFFmZ3E0NkZpN29uTnpwSTgKLS0tIERLQ0NPR2F5aW9rbFBlYlBBMlZ5
        dFRuUVhJZG52UURsaEJ1eFJMeUFSVXMKzVA4kxKnHGHBvRb0FgbrT2By2uKuENAK
        PUqyMWQEbN/NR3+DO+IyZWSEQTdVCxjUqcLOvZM/miOIl+jclD48qA==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age14uepygtepskwehywergh9fe9j2a3ytqd80y9r2ekfmett6rq3peqjtgxns
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtdFJRYnQzUWI5ayswdzdh
        eFg0dHEydk5ObWE4K1JzbnRiRHFaWHBvaldJCll3Ym5zSmtMM1BEVzY1TFRUT08r
        M2VrdTlpSVFsY3VJTkdwYW9jNCtwWU0KLS0tIFpsbUlSTi9TRzFOcFdFQjdJOTE1
        WnBtdUdpSE1WUUpKWUo4bXlJeHBKQXMKoGqTLLRCjk0kzIHF8DP1cIuZ/Gcm3mwa
        rOOBC781EQpuvCe7VlfhTsj2joIsM5shTwGi3s8vfdMVcxbCdwmwdg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-08-29T18:58:12Z"
  mac: ENC[AES256_GCM,data:1Gwzi1KBMBhbhd1+zuEdbpqg6uw9jZzaOW4+9MQgg50Gr5PH/r6UsVXBxfps3B2Hii/Wqzr1dUT+N8+2jWY1isFlXwwoUiiJuCcGsnrFsxA/aO/nKctC8C6477pEY0tgw93Ti+SE3quGVucCF5jIczc/4/AAtpyVuG7XTtcv7P0=,iv:uT+3o7pJdxfA7ZIShjZxpzj6SyQ+TQrNKRf5pSc9ZC8=,tag:Fo1oza1OHwdeY0L52pDang==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
