# Create metallb Helm release
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
spec:
  chart:
    spec:
      # Use this chart from the repository
      chart: metallb
      # Pin version to minor
      version: "0.14.x"
      # Use this Helm repository
      sourceRef:
        kind: HelmRepository
        name: metallb
  driftDetection:
    # This is needed because these resources are being mutated
    # See: https://github.com/metallb/metallb/issues/1681
    ignore:
      - paths:
          - /spec/conversion/webhook/clientConfig/caBundle
        target:
          group: apiextensions.k8s.io
          kind: CustomResourceDefinition
          name: bgppeers.metallb.io
      - paths:
          - /spec/conversion/webhook/clientConfig/caBundle
        target:
          group: apiextensions.k8s.io
          kind: CustomResourceDefinition
          name: addresspools.metallb.io
  # This key always needs to be here for patching to work
  postRenderers: []
  values:
    # Set the class for the LoadBalancer
    loadBalancerClass: metallb
