amber:
  credentials:
    admin:
      user: ENC[AES256_GCM,data:+DEcjsI=,iv:ew6zL9qdO6W29BNODZKDOXy6+/92FF+tUDeqqxt+Czk=,tag:UsNMqF8NGzE8mul6Rbgerw==,type:str]
      password: ENC[AES256_GCM,data:B5Ml1L/+XBWLCcgHzd4=,iv:wWUAgJgqlEr9rQB3BiZL0372xKfxqxGShamrb49cRdQ=,tag:LwtuJUqG6HTMlgDxgBqV7A==,type:str]
    readonly:
      user: ENC[AES256_GCM,data:eRwJXOhhlgc=,iv:Eib4keqGxrf6SKUrDZ2dszXHAFuyoR6eY38h3IZ5wVw=,tag:4nf3AoRAbMapAicpulAM9A==,type:str]
      password: ENC[AES256_GCM,data:7xFGkEtx5PGopqAW3JJybisGoapDsBKFuoU2Skw/ZZg=,iv:Ftpz8ct5XRUCONVhjwWzMXau+N76ViPZeerYpwmHanc=,tag:9BKPO5+TQ8lssiKNkKrpVw==,type:str]
    readwrite:
      user: ENC[AES256_GCM,data:+GX9aJ/8XG2P,iv:JASXowd7hfhFAGafQ9eAKuHruB1gI3r7nizkVPSccaQ=,tag:DkFoXzLZ1Nbk/IUyQbnImw==,type:str]
      password: ENC[AES256_GCM,data:vYD0BOOZLvDEITD4VD0+y8bGyPLzDWjO48y2yBTyulk=,iv:3edZfuIFgUeUfM3CQbzRhC6MkTahnRMHhZ6y9Xrt8Fk=,tag:AcpVfsdgjiPZwOcKQH6kHA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzNlNoR1NXY3RjR3BqWnJj
        Q0FUTHFqK3dJK3kyYjc5dE9rbkJFRzdRaG04CnNlQ0I2VUl6Tmt2TlNuSDdMQUNM
        MTFxQjJRTFFmZ3E0NkZpN29uTnpwSTgKLS0tIERLQ0NPR2F5aW9rbFBlYlBBMlZ5
        dFRuUVhJZG52UURsaEJ1eFJMeUFSVXMKzVA4kxKnHGHBvRb0FgbrT2By2uKuENAK
        PUqyMWQEbN/NR3+DO+IyZWSEQTdVCxjUqcLOvZM/miOIl+jclD48qA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1v3g2m2yl9jmu53r6h68fkllunvws389nseyp2waarul2m9r3we9sx0gfjt
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtdFJRYnQzUWI5ayswdzdh
        eFg0dHEydk5ObWE4K1JzbnRiRHFaWHBvaldJCll3Ym5zSmtMM1BEVzY1TFRUT08r
        M2VrdTlpSVFsY3VJTkdwYW9jNCtwWU0KLS0tIFpsbUlSTi9TRzFOcFdFQjdJOTE1
        WnBtdUdpSE1WUUpKWUo4bXlJeHBKQXMKoGqTLLRCjk0kzIHF8DP1cIuZ/Gcm3mwa
        rOOBC781EQpuvCe7VlfhTsj2joIsM5shTwGi3s8vfdMVcxbCdwmwdg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age14uepygtepskwehywergh9fe9j2a3ytqd80y9r2ekfmett6rq3peqjtgxns
  lastmodified: "2026-10-07T19:12:31Z"
  mac: ENC[AES256_GCM,data:yZyByZp7LaIsJ8w/ZpaJJQBlwAe70OIn8ZM3RrCXNBv7g/77LV6bgOcS9+ELsldeJzUxY1GUDGXA/Hhqmnel9rIBuadOHEYKDjq4+hOqW48D66a7FHYetntVk6al3vJX1np38jDZWJNHuThwa1kG9NbqdqBEfZtHNHRbmTnxgNc=,iv:Dc5xHkwQKBfqG4UC9gm/cijBUrx3iAaSLDAVnbNowaY=,tag:TjJYiaZlGoB+xBN9ByqyGA==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.3
