# Create trust-manager-config Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# Include the following configuration files
configurations:
  - configurations/names.yaml
# Include the following resources
resources:
  - resources/bundle.yaml
# Generate secrets
secretGenerator:
  - files:
      - ca.crt=secrets/ca.crt
    name: trust-manager-config-secrets-certificates
