# Create trust-manager-config Kustomization
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: trust-manager-config
spec:
  # Path inside repository to a directory containing Kustomization files
  path: src/clusters/main/infrastructure/trust-manager/kustomize/trust-manager-config/kustomize
  dependsOn:
    # Deploy Helm release first
    - name: trust-manager-helm
  # This key always needs to be here for patching to work
  patches: []
